name: Flomics CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  pull_request_review:
    types: [submitted]

jobs:
  flomics_test_corall_PE:
    env:
      NXF_VER: "23.10.1"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name : Clone nextflow-configs repo dev branch
        run: |
          mkdir -p ~/actions_workspace/src
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:Flomics/nextflow-configs.git'
          cd nextflow-configs/
          git checkout dev
          cd rnaseq/
          awk 'NF' Flomics_master_params.yml library_prep_kit/corall_PE_params.yml references/hg38_gencodev39_params.yml > params.yml
          cd
      - name: Clone and set up turret
        run: |
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY_TURRET }}" | ssh-add - && git clone git@github.com:Flomics/turret.git'
          cd turret/
          git checkout dev
          cd
      - name: Run pipeline with test data
        run: |
          cp -r ${GITHUB_WORKSPACE} ~/actions_workspace/src/rnaseq/
          cd ~/actions_workspace/src/

          aws s3 cp s3://flomics-data/test_data_RNAseq_pipeline/Flomics_rnaseq_test_PE_CORALL_samplesheet.csv .

          ~/actions_workspace/src/turret/turret/turret.sh \
          --repo_path rnaseq \
          --samplesheet Flomics_rnaseq_test_PE_CORALL_samplesheet.csv \
          --outdir s3://flomics-scratch/nextflow-workdir/test/test_corall_PE/ \
          --config ~/actions_workspace/src/nextflow-configs/rnaseq/Flomics_master.config \
          --config ~/actions_workspace/src/nextflow-configs/rnaseq/library_prep_kit/corall_PE.config \
          --params_file ~/actions_workspace/src/nextflow-configs/rnaseq/params.yml \
          --extra_args "-profile test_master,test_corall_PE,awsbatch --project GitHub_Actions"

  flomics_test_corall_SE:
    env:
      NXF_VER: "23.10.1"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name : Clone nextflow-configs repo dev branch
        run: |
          mkdir -p ~/actions_workspace/src
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:Flomics/nextflow-configs.git'
          cd nextflow-configs/
          git checkout dev
          cd rnaseq/
          awk 'NF' Flomics_master_params.yml library_prep_kit/corall_SE_params.yml references/hg38_gencodev39_params.yml > params.yml
          cd
      - name: Clone and set up turret
        run: |
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY_TURRET }}" | ssh-add - && git clone git@github.com:Flomics/turret.git'
          cd turret/
          git checkout dev
          cd
      - name: Run pipeline with test data
        run: |
          cp -r ${GITHUB_WORKSPACE} ~/actions_workspace/src/rnaseq/
          cd ~/actions_workspace/src/

          aws s3 cp s3://flomics-data/test_data_RNAseq_pipeline/Flomics_rnaseq_test_SE_CORALL_samplesheet.csv .

          ~/actions_workspace/src/turret/turret/turret.sh \
          --repo_path rnaseq \
          --samplesheet Flomics_rnaseq_test_SE_CORALL_samplesheet.csv \
          --outdir s3://flomics-scratch/nextflow-workdir/test/test_corall_SE/ \
          --config ~/actions_workspace/src/nextflow-configs/rnaseq/Flomics_master.config \
          --config ~/actions_workspace/src/nextflow-configs/rnaseq/library_prep_kit/corall_SE.config \
          --params_file ~/actions_workspace/src/nextflow-configs/rnaseq/params.yml \
          --extra_args "-profile test_master,test_corall_SE,awsbatch --project GitHub_Actions"

  flomics_test_smarter_PE:
    env:
      NXF_VER: "23.10.1"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name : Clone nextflow-configs repo dev branch
        run: |
          mkdir -p ~/actions_workspace/src
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:Flomics/nextflow-configs.git'
          cd nextflow-configs/
          git checkout dev
          cd rnaseq/
          awk 'NF' Flomics_master_params.yml library_prep_kit/smarter_PE_params.yml references/hg38_gencodev39_params.yml > params.yml
          cd
      - name: Clone and set up turret
        run: |
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY_TURRET }}" | ssh-add - && git clone git@github.com:Flomics/turret.git'
          cd turret/
          git checkout dev
          cd
      - name: Run pipeline with test data
        run: |
          cp -r ${GITHUB_WORKSPACE} ~/actions_workspace/src/rnaseq/
          cd ~/actions_workspace/src/

          aws s3 cp s3://flomics-data/test_data_RNAseq_pipeline/Flomics_rnaseq_test_PE_SMARTER_samplesheet.csv .

          ~/actions_workspace/src/turret/turret/turret.sh \
          --repo_path rnaseq \
          --samplesheet Flomics_rnaseq_test_PE_SMARTER_samplesheet.csv \
          --outdir s3://flomics-scratch/nextflow-workdir/test/test_smarter_PE/ \
          --config ~/actions_workspace/src/nextflow-configs/rnaseq/Flomics_master.config \
          --config ~/actions_workspace/src/nextflow-configs/rnaseq/library_prep_kit/smarter_PE.config \
          --params_file ~/actions_workspace/src/nextflow-configs/rnaseq/params.yml \
          --extra_args "-profile test_master,test_smarter_PE,awsbatch --project GitHub_Actions"

  flomics_test_smarter_SE:
    env:
      NXF_VER: "23.10.1"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name : Clone nextflow-configs repo dev branch
        run: |
          mkdir -p ~/actions_workspace/src
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:Flomics/nextflow-configs.git'
          cd nextflow-configs/
          git checkout dev
          cd rnaseq/
          awk 'NF' Flomics_master_params.yml library_prep_kit/smarter_SE_params.yml references/hg38_gencodev39_params.yml > params.yml
          cd
      - name: Clone and set up turret
        run: |
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY_TURRET }}" | ssh-add - && git clone git@github.com:Flomics/turret.git'
          cd turret/
          git checkout dev
          cd
      - name: Run pipeline with test data
        run: |
          cp -r ${GITHUB_WORKSPACE} ~/actions_workspace/src/rnaseq/
          cd ~/actions_workspace/src/

          aws s3 cp s3://flomics-data/test_data_RNAseq_pipeline/Flomics_rnaseq_test_SE_SMARTER_samplesheet.csv .

          ~/actions_workspace/src/turret/turret/turret.sh \
          --repo_path rnaseq \
          --samplesheet Flomics_rnaseq_test_SE_SMARTER_samplesheet.csv \
          --outdir s3://flomics-scratch/nextflow-workdir/test/test_smarter_SE/ \
          --config ~/actions_workspace/src/nextflow-configs/rnaseq/Flomics_master.config \
          --config ~/actions_workspace/src/nextflow-configs/rnaseq/library_prep_kit/smarter_SE.config \
          --params_file ~/actions_workspace/src/nextflow-configs/rnaseq/params.yml \
          --extra_args "-profile test_master,test_smarter_SE,awsbatch --project GitHub_Actions"
