name: Flomics CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev

jobs:
  flomics_test_corall_PE:
    env:
      NXF_VER: "22.10.0"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name : Clone nextflow-configs repo dev branch
        run: |
          mkdir -p ~/actions_workspace/src
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:Flomics/nextflow-configs.git'
          cd nextflow-configs/
          git checkout dev
          cd rnaseq/
          awk 'NF' Flomics_master_params.yml library_prep_kit/corall_PE_params.yml references/hg38_gencodev39_params.yml > params.yml
          cd
      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_master,test_corall_PE,awsbatch -c ~/actions_workspace/src/nextflow-configs/rnaseq/Flomics_master.config -c ~/actions_workspace/src/nextflow-configs/rnaseq/library_prep_kit/corall_PE.config -params-file ~/actions_workspace/src/nextflow-configs/rnaseq/params.yml

  flomics_test_corall_SE:
    env:
      NXF_VER: "22.10.0"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name : Clone nextflow-configs repo dev branch
        run: |
          mkdir -p ~/actions_workspace/src
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:Flomics/nextflow-configs.git'
          cd nextflow-configs/
          git checkout dev
          cd rnaseq/
          awk 'NF' Flomics_master_params.yml library_prep_kit/corall_SE_params.yml references/hg38_gencodev39_params.yml > params.yml
          cd
      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_master,test_corall_SE,awsbatch -c ~/actions_workspace/src/nextflow-configs/rnaseq/Flomics_master.config -c ~/actions_workspace/src/nextflow-configs/rnaseq/library_prep_kit/corall_SE.config -params-file ~/actions_workspace/src/nextflow-configs/rnaseq/params.yml

  flomics_test_smarter_PE:
    env:
      NXF_VER: "22.10.0"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name : Clone nextflow-configs repo dev branch
        run: |
          mkdir -p ~/actions_workspace/src
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:Flomics/nextflow-configs.git'
          cd nextflow-configs/
          git checkout dev
          cd rnaseq/
          awk 'NF' Flomics_master_params.yml library_prep_kit/smarter_PE_params.yml references/hg38_gencodev39_params.yml > params.yml
          cd
      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_master,test_smarter_PE,awsbatch -c ~/actions_workspace/src/nextflow-configs/rnaseq/Flomics_master.config -c ~/actions_workspace/src/nextflow-configs/rnaseq/library_prep_kit/smarter_PE.config -params-file ~/actions_workspace/src/nextflow-configs/rnaseq/params.yml

  flomics_test_smarter_SE:
    env:
      NXF_VER: "22.10.0"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name : Clone nextflow-configs repo dev branch
        run: |
          mkdir -p ~/actions_workspace/src
          cd ~/actions_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_DEPENDENCY }}" | ssh-add - && git clone git@github.com:Flomics/nextflow-configs.git'
          cd nextflow-configs/
          git checkout dev
          cd rnaseq/
          awk 'NF' Flomics_master_params.yml library_prep_kit/smarter_SE_params.yml references/hg38_gencodev39_params.yml > params.yml
          cd
      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_master,test_smarter_SE,awsbatch -c ~/actions_workspace/src/nextflow-configs/rnaseq/Flomics_master.config -c ~/actions_workspace/src/nextflow-configs/rnaseq/library_prep_kit/smarter_SE.config -params-file ~/actions_workspace/src/nextflow-configs/rnaseq/params.yml
