name: Flomics CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev

jobs:
  flomics_test_corall_PE:
    env:
      NXF_VER: "22.10.0"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with test data
        run: |
          # TODO nf-core: You can customize CI pipeline run tests as required
          # (eg. adding multiple test runs with different parameters)
          nextflow run ${GITHUB_WORKSPACE} -profile test_corall_PE,awsbatch

  flomics_test_corall_SE:
    env:
      NXF_VER: "22.10.0"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with test data
        run: |
          # TODO nf-core: You can customize CI pipeline run tests as required
          # (eg. adding multiple test runs with different parameters)
          nextflow run ${GITHUB_WORKSPACE} -profile test_corall_SE,awsbatch

  flomics_test_smarter_PE:
    env:
      NXF_VER: "22.10.0"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with test data
        run: |
          # TODO nf-core: You can customize CI pipeline run tests as required
          # (eg. adding multiple test runs with different parameters)
          nextflow run ${GITHUB_WORKSPACE} -profile test_smarter_PE,awsbatch

  flomics_test_smarter_SE:
    env:
      NXF_VER: "22.10.0"
      NXF_ANSI_LOG: false
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with test data
        run: |
          # TODO nf-core: You can customize CI pipeline run tests as required
          # (eg. adding multiple test runs with different parameters)
          nextflow run ${GITHUB_WORKSPACE} -profile test_smarter_SE,awsbatch
